export const accounts = {
    ["user1@example.com"]: {
        id: 1,
        user: "Jake",
        phoneNumber: "+67 6767 676 6767",
        email: "user1@example.com",
        password: "pass123",
        accountType: "Student",
        course: "Accounting",
        reservations: [
            {
                id: "R-MLHSJBZ4IY8I",
                labratory: "GK302A",
                dateTimeRequested: {
                    year: 2026,
                    month: 2,
                    day: 10,
                    time: { hour: 8, minute: 0 },
                },
                dateTimeSchedule: {
                    year: 2026,
                    month: 2,
                    day: 11,
                    time: { hour: 9, minute: 30 },
                },
                time: { hour: 9, minute: 30 },
                seat: 5,
                visibility: "Public",
                status: "Today",
            },
            {
                id: "R-6767JBZ4IY8I",
                labratory: "GK302A",
                dateTimeRequested: {
                    year: 2026,
                    month: 2,
                    day: 14,
                    time: { hour: 10, minute: 0 },
                },
                dateTimeSchedule: {
                    year: 2026,
                    month: 2,
                    day: 15,
                    time: { hour: 11, minute: 0 },
                },
                time: { hour: 11, minute: 0 },
                seat: 2,
                visibility: "Anonymous",
                status: "Upcoming",
            },
        ],
    },
    ["user2@example.com"]: {
        id: 2,
        user: "John Doe",
        phoneNumber: "#87-000",
        email: "user2@example.com",
        course: "Computer Science",
        password: "mypassword",
        accountType: "Student",
        reservations: [
            {
                id: "R-MLHSJBZ53RO6",
                labratory: "GK301",
                dateTimeRequested: {
                    year: 2026,
                    month: 2,
                    day: 9,
                    time: { hour: 13, minute: 30 },
                },
                dateTimeSchedule: {
                    year: 2026,
                    month: 2,
                    day: 10,
                    time: { hour: 14, minute: 15 },
                },
                time: { hour: 14, minute: 15 },
                seat: 3,
                visibility: "Public",
                status: "Past",
            },
        ],
    },
    ["user3@example.com"]: {
        id: 3,
        user: "Kane",
        email: "user3@example.com",
        password: "securepass",
        accountType: "Student",
        reservations: [
            {
                id: "R-MLHSJBZ53RO6",
                labratory: "GK302B",
                dateTimeRequested: {
                    year: 2026,
                    month: 2,
                    day: 18,
                    time: { hour: 9, minute: 0 },
                },
                dateTimeSchedule: {
                    year: 2026,
                    month: 2,
                    day: 20,
                    time: { hour: 10, minute: 0 },
                },
                time: { hour: 10, minute: 0 },
                seat: 1,
                visibility: "Anonymous",
                status: "Upcoming",
            },
            {
                id: "R-MLHSJBZ53RO6",
                labratory: "GK302B",
                dateTimeRequested: {
                    year: 2026,
                    month: 2,
                    day: 19,
                    time: { hour: 12, minute: 0 },
                },
                dateTimeSchedule: {
                    year: 2026,
                    month: 2,
                    day: 21,
                    time: { hour: 13, minute: 30 },
                },
                time: { hour: 13, minute: 30 },
                seat: 6,
                visibility: "Public",
                status: "Upcoming",
            },
        ],
    },
    ["admin1@example.com"]: {
        id: 4,
        email: "admin1@example.com",
        password: "adminpass",
        accountType: "Admin",
        reservations: [
            {
                id: "R-MLHSJBZ53RO6",
                labratory: "GK301",
                dateTimeRequested: {
                    year: 2026,
                    month: 2,
                    day: 10,
                    time: { hour: 7, minute: 30 },
                },
                dateTimeSchedule: {
                    year: 2026,
                    month: 2,
                    day: 11,
                    time: { hour: 8, minute: 0 },
                },
                time: { hour: 8, minute: 0 },
                seat: 10,
                visibility: "Public",
                status: "Today",
            },
            {
                id: "R-MLHSJBZ53RO6",
                labratory: "GK302B",
                dateTimeRequested: {
                    year: 2026,
                    month: 2,
                    day: 13,
                    time: { hour: 14, minute: 30 },
                },
                dateTimeSchedule: {
                    year: 2026,
                    month: 2,
                    day: 14,
                    time: { hour: 15, minute: 45 },
                },
                time: { hour: 15, minute: 45 },
                seat: 7,
                visibility: "Anonymous",
                status: "Upcoming",
            },
        ],
    },
    ["admin2@example.com"]: {
        id: 5,
        email: "admin2@example.com",
        password: "adminsecret",
        accountType: "Admin",
        reservations: [
            {
                id: "R-MLHSJBZ53RO6",
                labratory: "GK302A",
                dateTimeRequested: {
                    year: 2026,
                    month: 2,
                    day: 11,
                    time: { hour: 15, minute: 0 },
                },
                dateTimeSchedule: {
                    year: 2026,
                    month: 2,
                    day: 12,
                    time: { hour: 16, minute: 30 },
                },
                time: { hour: 16, minute: 30 },
                seat: 4,
                visibility: "Public",
                status: "Upcoming",
            },
        ],
    },
};
//# sourceMappingURL=accounts.js.map